# ------------------------------------------------------------------------------
# fencing-controller watches for the failed nodes and initializates fencing
# process
# ------------------------------------------------------------------------------

controller:
  enabled: true
  replicas: 2

  image:
    repository: ghcr.io/yosshy/kube-fencing/kube-fencing-controller
    tag: latest
    pullPolicy: Always
    pullSecrets:
      - name: regsecret

  nodeSelector: {}
  #  'node-role.kubernetes.io/master': ''

  tolerations: []
  #  - key: node-role.kubernetes.io/master
  #    operator: Exists
  #    effect: NoSchedule
  
# ------------------------------------------------------------------------------
# fencing-switcher enables and disables fencing for the node during graceful
# shutdown
# ------------------------------------------------------------------------------

switcher:
  enabled: true

  image:
    repository: ghcr.io/yosshy/kube-fencing/kube-fencing-switcher
    tag: latest
    pullPolicy: Always
    pullSecrets:
      - name: regsecret

  nodeSelector: {}
  #  'node-role.kubernetes.io/master': ''

  tolerations: []
  #  - key: node-role.kubernetes.io/master
  #    operator: Exists
  #    effect: NoSchedule

# ------------------------------------------------------------------------------
# Specify if a Pod Security Policy for linstor components must be created
# Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
# ------------------------------------------------------------------------------

podSecurityPolicy:
  enabled: false
