# Labels to apply to all resources
commonLabels: {}

# ------------------------------------------------------------------------------
# fencing-controller watches for the failed nodes and initializates fencing
# process
# ------------------------------------------------------------------------------

controller:
  enabled: true
  replicas: 2

  image:
    repository: ghcr.io/kvaps/kube-fencing-controller
    tag: v2.4.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  nodeSelector: {}
  #  'node-role.kubernetes.io/master': ''

  tolerations: []
  #  - key: node-role.kubernetes.io/master
  #    operator: Exists
  #    effect: NoSchedule
  
  topologySpreadConstraints: []
  #  - maxSkew: 1
  #    topologyKey: topology.kubernetes.io/zone
  #    whenUnsatisfiable: DoNotSchedule
  #    labelSelector:
  #      matchLabels:
  #        app: "foo"

# ------------------------------------------------------------------------------
# fencing-switcher enables and disables fencing for the node during graceful
# shutdown
# ------------------------------------------------------------------------------

switcher:
  enabled: true

  image:
    repository: ghcr.io/kvaps/kube-fencing-switcher
    tag: v2.4.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  nodeSelector: {}
  #  'node-role.kubernetes.io/master': ''

  tolerations: []
  #  - key: node-role.kubernetes.io/master
  #    operator: Exists
  #    effect: NoSchedule

# ------------------------------------------------------------------------------
# Specify if a Pod Security Policy for linstor components must be created
# Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
# ------------------------------------------------------------------------------

podSecurityPolicy:
  enabled: false
